spring:
  application:
    name: josue_tipan_shipflow
  datasource:
    url: jdbc:postgresql://localhost:5432/shipflow_db
    driver-class-name: org.postgresql.Driver
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect 